### ISSUE TITLE
k8s upgrade strategy 

### ISSUE THREAD

**Issue by axot** [ocgi/spec#1]
Thanks for sharing such great project solves many Agones pain points.
We have a question is, how the behavior when we perform k8s upgrade,
It is possible to build a HA architecture, so we could achieve zero downtime during k8s upgrade.

**Comment by hustcat** [comment]
@axot Thank you for your attention. Does `K8s upgrade` here refer to `K8s pod updating`, or `K8s components`, such as `kube-apiserver` upgrade?

**Comment by axot** [comment]
Hi, it include both control plane(Master/apiserver) and data plane(Node/Pod) upgrade we have to concern about.

**Comment by hustcat** [comment]
With [High-Availability Masters](https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/), we can upgrade the any K8s components online. Of course, the master node MUST be upgraded one by one.
For game application, a `Squad` consist of multiple `DS` replicas, we can rolling updating the replicas based on the [Application Interactive Update](https://github.com/ocgi/spec#main-features) feature, and don't  need to stop serving for game players.

**Comment by axot** [comment]
Hi, how about carrier controller? I think it will failover to the new leader in upgrade. So may has few seconds delayed response for such scale game server?

**Comment by hustcat** [comment]
Yeah, current the master lease is [15 seconds](https://github.com/ocgi/carrier/blob/master/cmd/controller/main.go#L50), which may cause a few seconds scaling delay when carrier upgrade.

**Comment by ringtail** [comment]
@axot Would you like to try kruise-game (https://github.com/openkruise/kruise-game)
