### ISSUE TITLE
Is there any sample implementation of Dedicated Server?

### ISSUE THREAD

**Issue by toVersus** [ocgi/spec#2]
Hi, I'm very impressed with the ideas around the OCGI but lacking in Agones, however I'm a little bit confused about what components should we implement for running Dedicated Server in carrier?
In the architecture diagram [1], we can see the `dsagent` in Dedicated Server and it manages some `ds` processes. 
Should we implement `ds` process manager (a.k.a. `dsagent`) by hand?

Are you planning to publish any sample implementation (e.g. `simple-tcp` in the official docs [2]) of Dedicated Server somewhere in this organization?

[1] https://github.com/ocgi/carrier#application-architecture-based-on-carrier
[2] https://github.com/ocgi/sdk-examples/tree/master/simple-tcp

**Comment by hustcat** [comment]
Hi @toVersus , thanks for you attention.
Here the `dsagent` and `ds` are example of `DS` architecture  in our game application, and they are all implemented by the game server developer. 
The [sdk-examples](https://github.com/ocgi/sdk-examples/tree/master/simple-tcp) is a very simple tcp server example with `Carrier`。

**Comment by toVersus** [comment]
Thanks for sharing an example!
I'm looking forward to see more examples including multiple `ds` processes pattern in single game server, but I will try to prototype it based on a simple tcp server example.

**Comment by ringtail** [comment]
> Thanks for sharing an example! I'm looking forward to see more examples including multiple `ds` processes pattern in single game server, but I will try to prototype it based on a simple tcp server example.

Try kruise-game (https://github.com/openkruise/kruise-game).
